
    <div class="sp-fixed-block sp-fix">
      <div class="sp-fixed-btn col2">
        <div class="sp-fixed-tel">
          <a href="#sp-golf-tel-block" class="open-popup">電話予約</a>
        </div>
        <div class="sp-fixed-searchbox">
          <a href="https://princegolfresort.jp/rsv_sys/prince/hakone-en/calendar" target="_blank">空き枠検索・予約</a>
        </div>
      </div>
    </div>
    <footer class="footer">
      <div class="footer-wrap">
      <div class="pagetop pc-fix"><a href="#"><img src="/images_static/common/pagetop.png" alt=""></a></div>
      <div class="footer-top">
        <div class="footer-sns">
        </div>
        <div class="footer-search">
                <form name="search_form" action="https://search.princehotels.co.jp/" method="get" onsubmit="return mysearch(this);">
                    <div class="footer-search-box cf">
                        <input type="text" id="freesearch" class="searchBox" name="kw" placeholder="何をお探しですか？">
                        <input type="hidden" name="ie" value="u" />
                        <input type="hidden" name="group" value="1" />
                        <input type="submit" class="searchButton" value="">
                    </div>
                </form>
            </div>
        <div class="footer-link">
          <ul class="cf">
            <li><a href="/golf/hakone-en/map/">アクセス</a></li>
            <li><a href="/golf/hakone-en/faq/">よくある質問</a></li>
          </ul>
        </div>
      </div>
      <div class="footer-nav">
        <div class="inner cf">
          <div class="box footer-nav-area">
            <div class="footer-inner">
              <ul>
                <li><a href="/golf/hakone-en/">トップページ</a></li>
                <li><a href="/pss/">ステータスクラブ</a></li>
              </ul>
              <ul>
                <li><a href="/golf/hakone-en/course/">コースレイアウト</a></li>
                <li><a href="/golf/hakone-en/tomonokai/">友の会のご案内</a></li>
              </ul>
              <ul>
                <li><a href="https://princegolfresort.jp/rsv_sys/prince/hakone-en/calendar" target="_blank">ご予約</a></li>
                <li><a href="/golf/hakone-en/informations/">お知らせ</a></li>
              </ul>
            </div>
            <div class="footer-inner">
              <ul>
                <li><a href="/golf/hakone-en/facility/">施設・レストランのご案内</a></li>
              </ul>
            </div>
          </div>
        </div>
      </div>
      <div class="footer-back">
        <ul class="footer-back-link">
          <li><a href="/golf/"><span>プリンスゴルフリゾーツ<br>トップページへ</span></a></li>
        </ul>
        <ul class="footer-back-logo">
          <li><a href="/golf/"><img src="/images_static/golf/golf_area_footer_logo_01.png" alt=""></a></li>
          <li><a href="https://www.seibuholdings.co.jp/group/" target="_blank"><img src="/images_static/wedding/footer_logo_seibu.png" alt=""></a></li>
        </ul>
        <div class="pagetop sp-fix"><a href="#"><img src="/images_static/common/pagetop.png" alt=""></a></div>
      </div>
      </div>
      <div class="footer-copy">
        <p>Copyright &copy; SEIBU PRINCE HOTELS WORLDWIDE INC. <br class=sp-fix>All rights reserved.</p>
      </div>
    <!-- /.footer =======--></footer>

	<style>
	.footer-nav,.footer-copy,.footer-back {
		line-height: 1.2;
	}

	@media screen and (max-width: 736px){
		.footer-copy p {
			font-size: 12px;
			line-height: 1.2;
		}
	}

	.footer-sns a {
		width: 42px;
	}

	.footer-sns p {
		line-height: 1.2;
	}

	.footer-sns img {
		vertical-align: middle;
	}

	.footer-link {
		line-height: 1.2;
	}
	</style>