<header class="header">
      <div class="header-top cf">
        <div class="sp-header-menu-btn"><a href="#sp-menu-block" class="open-popup"><img src="/images_static/common/sp_header_menu_btn.png" alt="MENU"></a></div>
        <div class="sp-header-menu-search"><a href="#sp-search-block" class="open-popup"><img src="/images_static/common/sp_header_search_btn.png" alt=""></a></div>
        <div class="header-menu cf">
          <div class="header-menu-btn"><img src="/images_static/area/header_menu_btn.png" alt=""></div>
          <p>西武プリンスホテルズ&amp;リゾーツ MENU</p>
          <div class="header-menu-box">
            <div class="header-menu-btn"><img src="/images_static/area/header_menu_close.png" alt=""></div>
            <p>西武プリンスホテルズ&amp;リゾーツ MENU</p>
            <ul>
                <li><a href="/">西武プリンスホテルズ&amp;リゾーツ HOME</a></li>
                <li><a href="https://www.seibuprince.com/ja/find-a-hotel">ホテル一覧</a></li>
                <li><a href="/features/">特集･イベント</a></li>
                <li><a href="/restaurant_cafe/">レストラン･バー</a></li>
                <li><a href="/mice/">会議･宴会</a></li>
                <li><a href="/wedding/">ウエディング</a></li>
                <li><a href="/spa_bath/">温泉・スパ</a></li>
                <li><a href="/golf/">ゴルフ</a></li>
                <li><a href="/ski/">スキー</a></li>
                <li><a href="/sports_amusement/">アミューズメント</a></li>
                <li><a href="https://www.seibuprince.com/ja/loyalty">会員サービス・特典</a></li>
                <li><a href="https://www.seibuprince.com/ja/brands">プリンスホテルブランドについて</a></li>
                <li>
                    <ul>
                    <li><a href="https://www.seibuprince.com/ja/support/faq">よくある質問</a></li>
                    <li><a href="https://www.seibuprince.com/ja/support">お問合せ</a></li>
                    </ul>
                </li>
              </ul>
          </div>
        </div>
        <h1 class="header-logo">
          <a href="/golf/hakone-en/"><img src="/golf/hakone-en/images_static/header_logo.png" alt="箱根園ゴルフ場" class="pc-fix"><img src="/golf/hakone-en/images_static/sp_header_logo.png" alt="" class="sp-fix"></a>
        </h1>
        <div class="header-util cf">
          <div class="header-lang">
            <div class="lang-active">JP</div>
            <div class="lang-box">
              <ul>
                <li class="active"><a href="/">日本語</a></li>
				<li><a href="http://www.princehotels.com/en/golf/hakone-en/">English</a></li>
              </ul>
            </div>
          </div>
          <div class="header-search">
            <form name="search_form" action="https://search.princehotels.co.jp/" method="get" target="_blank">
              <div class="header-search-box cf">
                    <input type="hidden" name="ref" value="" id="site-search-ref-pc" />
                <input type="text" id="freesearch" name="kw" value="" class="searchBox" />
                <input type="hidden" name="ie" value="u" />
                    <input type="hidden" name="by" value="js" />
                    <!--<input type="hidden" name="group" value="1" />-->
                <input type="submit" class="searchButton" value="&#xf002;" />
              </div>
            </form>

          </div>
          <div class="header-login header-login--member">
            <p class="open"><a href="/member/"><span class="fa fa-"></span>メンバーページ</a></p>
          </div>
        </div>
      </div>
      <div class="header-address">
        <p>箱根園ゴルフ場　〒250-0522 神奈川県足柄下郡箱根町元箱根138 TEL：0460-83-6555</p>
        <p class="header-address-access"><a href="/golf/hakone-en/map/">アクセス</a></p>
        <p class="header-address-access"><a style="width:80px" href="/golf/hakone-en/faq/">よくある質問</a></p>
      </div>
      <div class="header-nav cf">
        <nav>
          <ul class="cf">
            <li><a href="/golf/hakone-en/course/"><span>コースレイアウト</span></a></li>
            <li><a href="https://princegolfresort.jp/rsv_sys/prince/hakone-en/calendar" target="_blank"><span>ご予約</span></a></li>
            <li><a href="/golf/hakone-en/facility/"><span>施設・レストランのご案内</span></a></li>
            <li><a href="/golf/hakone-en/tomonokai/"><span>友の会のご案内</span></a></li>
            <li><a href="/golf/hakone-en/informations/"><span>お知らせ</span></a></li>
            <li><a href="/golf/hakone-en/map/"><span>アクセス・周辺案内</span></a></li>
          </ul>
        </nav>
      </div>
      <div class="sp-menu-block mfp-hide sp-modal" id="sp-menu-block">
        <div class="mfp-close"></div>
        <p class="menu-name">箱根園ゴルフ場</p>
        <div class="header-lang">
          <div class="lang-active">JP</div>
          <div class="lang-box">
             <ul>
              <li class="active"><a href="/">日本語</a></li>
				<li><a href="http://www.princehotels.com/en/golf/hakone-en/">English</a></li>
            </ul>
          </div>
        </div>
        <div class="sp-header-nav">
          <nav>
           <ul class="cf">
			  <li><a href="/golf/hakone-en/">トップページ</a></li>
			  <li><a href="/golf/hakone-en/course/">コースレイアウト</a></li>
			  <li><a href="https://princegolfresort.jp/rsv_sys/prince/hakone-en/calendar" target="_blank">ご予約</a></li>
			  <li><a href="/golf/hakone-en/facility/">施設・レストランのご案内</a></li>
			  <li><a href="/golf/hakone-en/tomonokai/">友の会のご案内</a></li>
			  <li><a href="/golf/hakone-en/informations/">お知らせ</a></li>
			  <li><a href="/golf/hakone-en/faq/">よくある質問</a></li>
            <li>
              <ul>
                <li class="tel"><a href="#sp-golf-tel-block" class="open-popup">電話</a></li>
                <li class="access"><a href="/golf/hakone-en/map/">アクセス・周辺案内</a></li>
              </ul>
            </li>
          </ul>
          </nav>
        </div>
        <!--
        <div class="sp-header-util">
          <ul>
            <li><a href="https://www.seibuprince.com/ja/support/faq">よくある質問</a></li>
          </ul>
        </div>
        -->
        <p class="back"><a href="/golf/">プリンスゴルフリゾーツ<br>トップページへ</a></p>
        <div class="mfp-close-bottom">
          <div class="mfp-close"></div>
        </div>
      </div>
      <div class="sp-search-block mfp-hide sp-modal" id="sp-search-block">
        <div class="mfp-close"></div>
        <form name="search_form" action="https://search.princehotels.co.jp/" method="get" target="_blank">
          <div class="header-search-box cf">
            <input type="hidden" name="ref" value="" id="site-search-ref-sp" />
            <input type="text" name="kw" class="searchBox" placeholder="何をお探しですか？">
            <input type="hidden" name="ie" value="u" />
            <input type="hidden" name="by" value="js" />
            <!--<input type="hidden" name="groups" value="1" />-->
            <input type="submit" value="">
          </div>
        </form>
        <div class="u-center">
          <ul>
            <li class="link"><a href="/support/faq/">よくある質問</a></li>
          </ul>
        </div>
        <div class="mfp-close-bottom">
          <div class="mfp-close"></div>
        </div>
      </div>
      <div class="sp-login-block mfp-hide sp-modal" id="sp-login-block">
        <div class="mfp-close"></div>
        <p class="head">西武プリンスホテルズ&amp;リゾーツ会員ログイン<span>あなたに最適な情報をお届けします</span></p>
        <form action="">
          <div class="header-login-box cf">
            <p>お客様番号（SPC会員番号）</p>
            <input type="text" placeholder="お客様番号（半角）">
          </div>
          <div class="header-login-box cf">
            <p>ログインパスワード</p>
            <input type="text" placeholder="ログインパスワード（半角）">
          </div>
          <div class="header-login-check">
            <input type="checkbox" id="login-check">
            <label for="login-check">ログインしたままにする</label>
            <p><a href="#">パスワードをお忘れの方</a></p>
          </div>
          <div class="header-login-btn">
            <input type="submit" value="ログイン">
          </div>
        </form>
        <div class="header-login-note">
          <p>西武プリンスホテルズ&amp;リゾーツ会員ページのご利用には、<a href="#">SEIBU
            PRINCE CLUB</a>の会員登録が必要です。SEIBU PRINCE CLUB
            にご入会後、会員情報登録がお済みのお客さまはご利⽤いただけます。<br>※SEIBU PRINCE CLUBのWebお申込みは、お申込みと同時に「お客さま番号」を発番いたしますので、カードが届く前にマイページをご利用いただけます。</p>
          <p class="link"><a href="#">会員制度・特典を見る</a></p>
        </div>
        <div class="mfp-close-bottom">
          <div class="mfp-close"></div>
        </div>
      </div>
      <ul class="golf-fix cf header-fix" style="">
            <li class="tel popup-menu">
              <p class="open pc-fix"><span>電話予約</span></p>
              <p class="open sp-fix"><a href="#sp-golf-tel-block" class="open-popup">電話予約</a></p>
              <p class="close"></p>
              <div class="popup-menu-cont golf-tel-cont">
                <div class="sp-modal golf-tel-block" id="sp-golf-tel-block">
                  <div class="mfp-close"></div>
                  <div class="open-popup-cont">
                    <h2>電話でのご予約</h2>
                    <div class="main-cont">
                      <div class="sp-tel-info">
                        <h3>箱根園ゴルフ場</h3>
                        <p class="num"><span class="pc-tel">0460-83-6555</span><a href="tel:0460836555" class="sp-tel">0460-83-6555</a></p>
                      </div>
                    </div>
                   <!--  <div class="member-cont">
                      <h3>プリンスステータス ゴールドメンバー <br class="sp-fix">コンシェルジュデスク</h3>
                      <p class="lead">西武プリンスホテルズ＆リゾーツのご予約および<br> プリンスステータスサービスのお問合せはこちらから</p>
                      <div class="sp-tel-info status-gold">
                        <p class="num"><span class="pc-tel">0120-08-1111</span><a href="tel:0120081111" class="sp-tel">0120-08-1111</a></p>
                        <p class="note">9:00A.M.〜9:00P.M.（年末年始を除く）</p>
                      </div>
                    </div> -->
                    <div class="mfp-close-bottom">
                      <div class="mfp-close"></div>
                    </div>
                  </div>
                </div>
              </div>
            </li>
            <li class="searchbox popup-menu">
              <p class="open"><a href="https://princegolfresort.jp/rsv_sys/prince/hakone-en/calendar" target="_blank">空き枠検索・予約</a></p>
             <!--  <p class="close"></p> -->
              <!-- <div class="golf-searchbox-cont popup-menu-cont">
                <div class="sp-modal golf-reserve-popup" id="sp-golf-searchbox-block">
                  <div class="mfp-close"></div>
                  <div class="open-popup-cont">
                    <div class="golf-reserve">
                      <div class="head">
                        <h3>コースの空き枠検索・予約</h3>
                        <p><a href="#">SEIBU PRINCE CLUB会員</a>の皆さまには、最もお得な料金の保証や、様々な特典をご用意しております。</p>
                      </div>
                      <div class="body">
                        <div class="form">
                          <div class="form-cont reserve-body-input">
                            <p class="head02 sp-fix">プレー候補日を指定</p>
                            <form action="">
                              <div class="area">
                                <ul class="filter">
                                  <li class="active"><a href="#">都道府県</a></li>
                                  <li><a href="#">ゴルフ場</a></li>
                                </ul>
                                <select>
                                  <option selected="selected">全地域</option>
                                </select>
                              </div>
                              <div class="date cf">
                                <span class="title pc-fix">プレー候補日を指定</span>
                                <div class="block">
                                  <select>
                                    <option selected="selected">— —</option>
                                  </select>
                                  <span>月</span>
                                  <select>
                                    <option selected="selected">— —</option>
                                  </select>
                                  <span>日から</span>
                                  <select>
                                    <option selected="selected">— —</option>
                                  </select>
                                  <span class="pr20">日間</span>
                                </div>
                                <div class="block">
                                  <input type="radio" value="曜日指定しない" name="radio02" id="radio04" class="radio-type01">
                                  <label for="radio04">曜日指定しない</label>
                                  <input type="radio" value="平日" name="radio02" id="radio05" class="radio-type01">
                                  <label for="radio05">平日</label>
                                  <input type="radio" value="土日祝" name="radio02" id="radio06" class="radio-type01">
                                  <label for="radio06">土日祝</label>
                                </div>
                              </div>
                              <div class="price cf">
                                <span class="title">プレー料金を指定</span>
                                <div class="block">
                                  <select>
                                    <option selected="selected">指定しない</option>
                                  </select>
                                  <span class="pr">円～</span>
                                  <select>
                                    <option selected="selected">指定しない</option>
                                  </select>
                                  <span>円</span>
                                </div>
                              </div>
                              <div class="reserve-body-submit">
                                <button type="submit">検索する</button>
                              </div>
                            </form>
                          </div>
                          <div class="entry">
                            <p><a href="#">My Prince Golfログイン・会員登録<br><span>（Web予約 確認・変更）</span></a></p>
                          </div>
                        </div>
                        <div class="bnr">
                          <div class="box box01">
                            <a href="#">友の会会員の皆さまにお得にご予約いただける<br><span>「友の会限定予約」</span>はこちら</a>
                          </div>
                          <div class="box box02">
                            <a href="#">メンバーシップの皆さまにお得にご予約いただける<br><span>「メンバーシップ限定予約」</span>はこちら</a>
                          </div>
                        </div>
                        <p class="note">※株主優待券・割引券をご利用の際は、ご予約時にその旨をお伝え下さい。また、Web予約では『ゴルフ場へのご要望』欄へご記入ください。</p>
                      </div>
                    </div>
                    <div class="mfp-close-bottom">
                      <div class="mfp-close"></div>
                    </div>
                  </div>
                </div>
              </div> -->
            </li>
          </ul>
<!-- /.header =======--></header>
<style>

.area .header-login p{
	padding: 0 10px;
	position: relative;
}
.area .header-login--member {
    width: 150px;
}
.golf .golf-fix li.searchbox p.open  {
  background: url("/images_static/golf/golf_icon_arrow_right_01.png") 94% center no-repeat #0E7134;
  background-size: 22px auto;
  width: 190px;
  padding-left: 25px;
}
.golf .golf-fix li.searchbox p.open a{
  text-decoration: none;
  color: #fff;
}
.golf .golf-fix li.searchbox p.open a[target='_blank']:after{
	display: none;
}
@media screen and (max-width: 736px){
	.area .header-login--member {
		width: 110px;
	}
	.area .header-login p {
		padding: 0 10px 0 5px;
		position: relative;
	}
	.header-login.header-login--member a:before {
		content: "\f007";
		font-size: 13px;
	}
	.header-login.header-login--member p.open:after{
		right: 2px;
	}
	.golf .sp-fixed-searchbox a:after{
		display: none;
	}
	.golf .sp-fixed-searchbox a{
		background: url("/images_static/golf/golf_icon_arrow_right_01.png") 94% center no-repeat #0E7134;
		background-size: 22px auto;
	}
	.golf .sp-fixed-searchbox:after{
		display: none;
	}
}
</style>
