<div class="sp-fixed-block sp-fix">
  <div class="sp-fixed-btn">
    <div class="sp-fixed-tel">
      <a href="#sp-tel-block" class="open-popup">電話予約</a>
    </div>
    <div class="sp-fixed-reserve">
      <a href="#sp-reserve-block" class="open-popup">空室検索・予約</a>
    </div>
  </div>
</div>

<footer class="footer">
      <div class="pagetop pc-fix"><a href="#"><img src="/images_static/common/pagetop.png" alt=""></a></div>
      <div class="footer-top">
        <div class="footer-sns">
          <p></p><ul></ul>
          <p>

沖縄プリンスホテル オーシャンビューぎのわん<br>ソーシャル公式</p>
          <ul>
			<li><a href="https://www.facebook.com/沖縄プリンスホテル-オーシャンビューぎのわん-103929185543973" target="_blank"><i class="fa fa-facebook" aria-hidden=true></i></a></li>
			<li><a href="https://twitter.com/okinawa_prince" target="_blank"><i class="fa fa-twitter" aria-hidden=true target=_blank></i></a></li>
            <li><a href="https://www.instagram.com/okinawaprincehotel_ginowan/"><i class="fa fa-instagram" aria-hidden=true></i></a></li>
          </ul>
          
        </div>
        <div class="footer-search">
          <form name="search_form" action="https://search.princehotels.co.jp/" method="get" onsubmit="return footsearch(this);">
            <div class="footer-search-box cf">
              <input type="text" placeholder="何をお探しですか？" name="kwf" />
                <input type="hidden" name="ief" value="u" />
                

<input type="hidden" name="group" value="19"/>
              <input type="submit" value="">
            </div>
          </form>
        </div>
        <div class="footer-link">
          <ul class="cf">
            <li><a href="/ginowan/access/">アクセス</a></li>
            <li><a href="/ginowan/faq/">よくあるご質問</a></li>
            <li><a href="/support/">お問合せ</a></li>
          </ul>
        </div>
      </div>
      <div class="footer-nav">
        <div class="inner cf">
          <div class="box footer-nav-area">
              <div class="footer-inner">
              <ul>
      <li><a href="/ginowan/">トップページ</a></li>
      <li><a href="/ginowan/plan/all">宿泊プラン一覧</a></li>
      <li><a href="/ginowan/room/">客室一覧</a></li>
              </ul>
              <ul>
      <li><a href="https://www.tour-list.com/TL/?hc=OK504" target="_new">宿泊＋飛行機</a></li>
      <li><a href="/ginowan/restaurant/">レストラン</a></li>
	  <!--<li><a href="/ginowan/facility/activitys/">観光・アクティビティー</a></li>-->
	  <li><a href="/ginowan/facility#se04">スパ・フィットネス</a></li>
              </ul>
            </div>
            <div class="footer-inner">
              <ul>
    <!--<li><a href="/ginowan/informations/?tab=event">イベント</a></li>-->
	
      <li><a href="/ginowan/facility/">施設案内</a></li>
	  <li><a href="/ginowan/access/">周辺案内</a></li>
              </ul>
              <!--<ul class="footer-business">
      <li><a href="/ginowan/access/">周辺案内</a></li>
              </ul>-->
            </div>
          </div>
        </div>
      </div>
      <div class="footer-nav footer-nav02">
        <div class="inner cf">
          <div class="box footer-nav-area02">
            <p class="title">プリンスホテルズ&amp;リゾーツ</p>
            <div class="wrap">
              <ul>
                <li class="txt-s"><a href="/membership/">会員サービス・特典</a></li>
              </ul>
              <ul>
                <li class="txt-s"><a href="/about/">プリンスホテルブランドについて</a></li>
                <li class="txt-s"><a href="/hotels_resorts/list/">ホテル一覧</a></li>
                <li class="txt-s"><a href="/company/outline/">会社情報</a></li>
                <li class="txt-s"><a href="/company/recruit/">採用情報</a></li>
                <li class="txt-s"><a href="/informations/">お知らせ・プレスリリース</a></li>
              </ul>
            </div>
            <div class="wrap">
              <ul>
<li class="txt-s"><a href="/selection/">プリンスホテルセレクション</a></li>
<li class="txt-s"><a href="/sitemap/">サイトマップ</a></li>
<li class="txt-s"><a href="/sitepolicy/">サイトポリシー</a></li>
<li class="txt-s"><a href="/company/privacypolicy/">個人情報保護方針</a></li><li class="txt-s"><a href="/transaction/">特定商取引法に基づく表記</a></li>
<li class="txt-s"><a href="/company/group/">西武グループ</a></li>
              </ul>
            </div>
          </div>
        </div>
        <div class="footer-nav-wrap cf">
          <div class="footer-nav-app">
            <p>SEIBU PRINCE CLUB 公式アプリ</p>
            <ul>
              <li><a href="https://apps.apple.com/jp/app/id1504829657?mt=8" target="_blank"><img src="/images_static/common/footer_bnr_app.png" alt="App Storeからダウンロード"></a></li>
              <li><a href="https://play.google.com/store/apps/details?id=jp.seibugroup.club" target="_blank"><img src="/images_static/common/footer_bnr_google.png" alt="Google Playで手に入れよう"></a></li>
            </ul>
          </div>
          <div class="pagetop sp-fix"><a href="#"><img src="/images_static/common/pagetop.png" alt=""></a></div>
        </div>
      </div>
      <div class="footer-back">
        <p class="pc-fix">
          <a href="/"><img src="/images_static/area/footer_arrow.png" alt="">
            <img src="/images_static/area/footer_logo.png" alt="">
          プリンスホテルズ&amp;リゾーツHOMEへ</a>
        </p>
        <p class="sp-fix text">
          <a href="/"><img src="/images_static/area/sp_footer_arrow.png" alt="">
          プリンスホテルズ&amp;リゾーツHOMEへ</a>
        </p>
        <p class="sp-fix"><a href="/"><img src="/images_static/area/footer_logo.png" alt=""></a></p>
        <p class="footer-seibu"><a href="https://www.seibuholdings.co.jp/group/"><img src="/images_static/area/footer_seibu.png" alt=""></a></p>
      </div>
      <div class="footer-copy">
        <p>Copyright &copy; SEIBU PRINCE HOTELS WORLDWIDE INC. <br class=sp-fix>All rights reserved.</p>
      </div>
    <!-- /.footer =======--></footer>
<script>
function footsearch (t) {
  var ref = location.href;
  var url = "https://search.princehotels.co.jp/?ref=" + ref.slice(0, ref.indexOf("#")) + "&kw=" + $('[name=kwf]').val() + "&ie=" + $('[name=ief]').val() + "&by=js" + "&group=" + $('[name=group]').val();
  window.open(url,'_blank');
  return false;
}

</script>