<header class="header">
      <div class="header-top cf">
        <div class="sp-header-menu-btn"><a href="#sp-menu-block" class="open-popup"><img src="/images_static/common/sp_header_menu_btn.png" alt="MENU"></a></div>
        <div class="sp-header-menu-search"><a href="#sp-search-block" class="open-popup"><img src="/images_static/common/sp_header_search_btn.png" alt=""></a></div>
        <div class="header-menu cf">
          <div class="header-menu-btn"><img src="/images_static/area/header_menu_btn.png" alt=""></div>
          <p>プリンスホテルズ&amp;リゾーツ MENU</p>
          <div class="header-menu-box">
            <div class="header-menu-btn"><img src="/images_static/area/header_menu_close.png" alt=""></div>
            <p>プリンスホテルズ&amp;リゾーツ MENU</p>
            <ul>
              <li><a href="/">プリンスホテルズ&amp;リゾーツ HOME</a></li>
              <li><a href="/hotels_resorts/list/">ホテル一覧</a></li>
              <li><a href="/features/">特集･イベント</a></li>
              <li><a href="/restaurant_cafe/">レストラン･バー</a></li>
              <li><a href="/mice/">会議･宴会</a></li>
              <li><a href="/wedding/">ウエディング</a></li>
              <li><a href="/spa_bath/">温泉・スパ</a></li>
              <li><a href="/golf/">ゴルフ</a></li>
              <li><a href="/ski/">スキー</a></li>
              <li><a href="/sports_amusement/">アミューズメント</a></li>
              <li><a href="/membership/">会員サービス・特典</a></li>
              <li><a href="/about/">プリンスホテルブランドについて</a></li>
              <li>
                <ul>
                  <li><a href="/support/faq/">よくある質問</a></li>
                  <li><a href="/support/">お問合せ</a></li>
                </ul>
              </li>
            </ul>
          </div>
        </div>
        <h1 class="header-logo">
          <a href="/ginowan/"><img src="/ginowan/images_static/header_logo.png" alt="" class="pc-fix"><img src="/ginowan/images_static/sp_header_logo.png" alt="" class="sp-fix"></a>
        </h1>
        <div class="header-util cf">
          <div class="header-lang">
            <div class="lang-active">JP</div>
            <div class="lang-box">
                <ul>
                  <li class="active"><a>日本語</a></li>
		　<li><a href="https://www.princehotels.com/ginowan/">English</a></li>
		　<li><a href="https://www.princehotels.cn/ginowan/zh-hans/">簡体中文</a></li>
		　<li><a href="https://www.princehotels.com/ginowan/zh-hant/">繁体中文</a></li>
		　<li><a href="https://www.princehotels.com/ginowan/ko/">&#54620;&#44397;&#50612;</a></li>
                </ul>
              </div>
            </div>
          <div class="header-search">
            <form name="search_form" action="https://search.princehotels.co.jp/" method="get" target="_blank">
                <div class="header-search-box cf">
                    <input type="hidden" name="ref" value="" id="site-search-ref-pc" />
                    <input type="text" id="freesearch" name="kw" value="" class="searchBox" />
                    <input type="hidden" name="ie" value="u" />
                    <input type="hidden" name="by" value="js" />
                    <input type="submit" class="searchButton" value="&#xf002;" />
                    

<input type="hidden" name="group" value="19"/>
                </div>
            </form>
          </div>
          <div class="header-login">
            <p class="open"><a href="/member/">メンバーページ</a></p>
          </div>
          <div class="header-fix">
            <div class="header-tel">
              <p class="open">電話での宿泊予約</p>
              <p class="close"></p>
              <div class="header-tel-cont">
                <div class="sp-tel-block sp-modal" id="sp-tel-block">
                  <div class="mfp-close"></div>
                  <div class="sp-reserve-head">
                    <h2><span>電話からの宿泊予約</span></h2>
                    <div class="hotel-tel">
                      <p>沖縄プリンスホテル オーシャンビューぎのわん</p>
                      <p class="num"><span class="pc-tel">098-898-1110</span><a href="tel:0988981110" class="sp-tel">098-898-1110</a></p>
                    </div>
                  </div>
                  <div class="sp-reserve-bottom">
                    <p class="head sp-fix">プリンスホテル予約センター</p>
                    <p class="lead">全国のプリンスホテルのご予約をお電話ひとつでご案内。<br class="pc-fix">24時間安心サポート！</p>
                    <div class="sp-tel-info">
                      <p class="num"><img src="/images_static/common/icon_free.png" alt="フリーダイヤル"><span class="pc-tel">0120-00-8686</span><a href="tel:0120008686" class="sp-tel">0120-00-8686</a></p>
                      <p class="note"><span>24時間対応・年中無休</span><br class="sp-fix">日本語、英語、中国語、韓国語対応</p>
                      <p class="navi">[ナビダイヤル] 　<span class="pc-tel">0570-01-8686</span><a href="tel:0570018686" class="sp-tel">0570-01-8686</a></p>
                    </div>
                    <p class="head pc-fix">プリンスホテル予約センター</p>
                    <p>※PHSや一部の携帯電話・IP電話・海外からのお電話などで「フリーダイヤル」「ナビダイヤル」への通話ができない場合はTEL：<span class="pc-tel">03-6741-9155</span><a href="tel:0367419155" class="sp-tel">03-6741-9155</a>をご利用ください。<br><br class="pc-fix">
                    ※プリンスホテルではお客さまサービス向上のため、通話を記録させていただいております。</p>
                    <div class="sp-header-util">
                      <ul>
                        <li><a href="/ginowan/faq/">よくある質問</a></li>
                        <li><a href="/support/">お問合せ先一覧</a></li>
                      </ul>
                    </div>
                  </div>
                  <div class="mfp-close-bottom">
                    <div class="mfp-close"></div>
                  </div>
                </div>
              </div>
            </div>
            <div class="header-reserve">
              <p class="open">空室検索・予約</p>
              <p class="close"></p>
              <div class="header-reserve-cont">
                <div class="reserve-body cf sp-modal" id="sp-reserve-block">
                  <div class="mfp-close"></div>
                  <form action="https://rsv.princehotels.co.jp/cgi-bin/ihonex/stay/search_plan.cgi" method="get" target="_blank" id="header-search-hotel-form">
                      <input type="hidden" name="form" value="jp"/>
                      <input type="hidden" name="search:area" value="09">
                      <input type="hidden" name="search:hid" value="098">
                      
                      <div class="reserve-body-input cf">
                     <h2><span>空室検索・予約</span></h2>
                      <p class="note"><a href="/membership/">SEIBU PRINCE CLUB会員</a>の皆さまには、<br class="sp-fix">最もお得な宿泊料金を保証させていただきます。</p>
                      <p class="name">

沖縄プリンスホテル オーシャンビューぎのわん</p>
                      <div class="wrap">
                        <div class="top cf">
                          <div class="date">
                            <span>チェックイン/チェックアウト</span>
                            <div class="datepicker">
                              <i class="fa fa-calendar" aria-hidden="true"></i>
                              <input type="text" id="datefrom" readonly="readonly"><span>〜</span>
                              <i class="fa fa-calendar" aria-hidden="true"></i>
      <input type="text" id="dateto" readonly="readonly">
                            </div>
                          </div>
                          <div class="num person-num">
                            <span>1室の<br class="sp-fix">ご利用人数</span>
                            <select name="search:ninzu">
                              <option value="1">1</option>
                              <option value="2" selected="selected">2</option>
                              <option value="3">3</option>
                              <option value="4">4</option>
                              <option value="5">5</option>
                              <option value="6">6</option>
                              <option value="7">7</option>
                              <option value="8">8</option>
                            </select>
                            <span>名</span>
                          </div>
                          <div class="num room-num">
                            <span>部屋数</span>
                            <select name="rooms">
                              <option value="1" selected="selected">1</option>
                              <option value="2">2</option>
                              <option value="3">3</option>
                              <option value="4">4</option>
                            </select>
                            <span>室</span>
                          </div>
                        </div>
                      </div>
                    </div>
                    <div class="reserve-body-submit">
                      <button type="button" id="header-search-hotel-button">検索する</button>
                    </div>
                  </form>
                  <div class="sp-reserve-bottom">
                    <div class="sp-header-util">
                      <ul>
                        <li><a href="/ginowan/faq/">よくある質問</a></li>
                        <li><a href="/support/">お問合せ</a></li>
                      </ul>
                    </div>
                    <p class="link"><a href="/rsv_information/infotop-ja.html">予約確認・キャンセル</a></p>
                  </div>
                  <div class="mfp-close-bottom">
                    <div class="mfp-close"></div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="header-address">
        <p>沖縄プリンスホテル オーシャンビューぎのわん 〒901-2224 沖縄県宜野湾市真志喜3丁目28-1 TEL：098-898-1110</p>
        <p class="header-address-access"><a href="/ginowan/access/">アクセス</a></p>
        <p class="header-address-access"><a style="width:80px" href="/ginowan/faq/">よくある質問</a></p>
      </div>
      <div class="header-nav cf">
  <nav>
    <ul class="cf">
    <!-- PCグローバルメニュー -->
      <li><a href="/ginowan/plan/all"><span>宿泊プラン一覧</span></a></li>
      <li><a href="/ginowan/room/"><span>客室一覧</span></a></li>
      <li><a href="https://www.tour-list.com/TL/?hc=OK504" target="_new"><span>宿泊＋飛行機</span></a></li>
      <li><a href="/ginowan/restaurant/"><span>レストラン</span></a></li>
      <!--<li class="fs_12"><a href="/ginowan/facility/activitys/"><span>観光・アクティビティー</span></a></li>
      <li><a href="/ginowan/informations/?tab=event"><span>イベント</span></a></li>-->
      <li><a href="/ginowan/facility#se04"><span>スパ・フィットネス</span></a></li>
      <li><a href="/ginowan/facility/"><span>施設案内</span></a></li>
      <li><a href="/ginowan/access/"><span>周辺案内</span></a></li>
    <!-- /SPグローバルメニュー-->
    </ul>
  </nav>
</div>
<div class="sp-menu-block mfp-hide sp-modal" id="sp-menu-block">
  <div class="mfp-close"></div>
  <div class="header-lang">
    <div class="lang-active">JP</div>
            <div class="lang-box">
              <ul>
                <li class="active"><a>日本語</a></li>
		　<li><a href="https://www.princehotels.com/ginowan/">English</a></li>
		　<li><a href="https://www.princehotels.cn/ginowan/zh-hans/">簡体中文</a></li>
		　<li><a href="https://www.princehotels.com/ginowan/zh-hant/">繁体中文</a></li>
		　<li><a href="https://www.princehotels.com/ginowan/ko/">&#54620;&#44397;&#50612;</a></li>
              </ul>
            </div>
  </div>
  <div class="sp-header-nav">
    <nav>
    <ul class="cf">
    <!-- SPグローバルメニュー -->
      <li><a href="/ginowan/">トップページ</a></li>
      <li><a href="/ginowan/plan/all">宿泊プラン一覧</a></li>
      <li><a href="/ginowan/room/">客室一覧</a></li>
      <li><a href="https://www.tour-list.com/TL/?hc=OK504" target="_new">宿泊＋飛行機</a></li>
      <li><a href="/ginowan/restaurant/">レストラン</a></li>
      <!--<li><a href="/ginowan/facility/activitys/">観光・アクティビティー</a></li>
      <li><a href="/ginowan/informations/?tab=event">イベント</a></li>-->
      <li><a href="/ginowan/facility#se04">スパ・フィットネス</a></li>
      <li><a href="/ginowan/facility/">施設案内</a></li>
      <li><a href="/ginowan/access/">周辺案内</a></li>
    <!-- /SPグローバルメニュー-->
              <li>
                <ul>
                  <li class="tel"><a href="tel:0987-64-2111">電話</a></li>
                  <li class="access"><a href="/ginowan/access/">アクセス</a></li>
                </ul>
              </li>
            </ul>
          </nav>
        </div>
        <div class="sp-header-util">
          <ul>
            <li><a href="/ginowan/faq/">よくある質問</a></li>
            <li><a href="/support/">お問合せ</a></li>
          </ul>
        </div>
        <p class="back"><a href="/">プリンスホテルズ&amp;リゾーツ HOMEへ</a></p>
        <div class="mfp-close-bottom">
          <div class="mfp-close"></div>
        </div>
      </div>
      <div class="sp-search-block mfp-hide sp-modal" id="sp-search-block">
        <div class="mfp-close"></div>
        <form name="search_form" action="https://search.princehotels.co.jp/" method="get" target="_blank">
          <div class="header-search-box cf">
            <input type="hidden" name="ref" value="" id="site-search-ref-sp" />
            <input type="text" name="kw" class="searchBox" placeholder="何をお探しですか？">
            <input type="hidden" name="ie" value="u" />
            <input type="hidden" name="by" value="js" />
            <!--<input type="hidden" name="groups" value="1" />-->
            <input type="submit" value="">
          </div>
        </form>
        <p class="link"><a href="/support/faq/">よくある質問</a></p>
        <div class="mfp-close-bottom">
          <div class="mfp-close"></div>
        </div>
      </div>
      <div class="sp-login-block mfp-hide sp-modal" id="sp-login-block">
        <div class="mfp-close"></div>
        <p class="head">プリンスホテルズ&amp;リゾーツ会員ログイン<span>あなたに最適な情報をお届けします</span></p>
        <form action="">
          <div class="header-login-box cf">
            <p>お客様番号（SPC会員番号）</p>
            <input type="text" placeholder="お客様番号（半角）">
          </div>
          <div class="header-login-box cf">
            <p>ログインパスワード</p>
            <input type="text" placeholder="ログインパスワード（半角）">
          </div>
          <div class="header-login-check">
            <input type="checkbox" id="login-check">
            <label for="login-check">ログインしたままにする</label>
            <p><a href="#">パスワードをお忘れの方</a></p>
          </div>
          <div class="header-login-btn">
            <input type="submit" value="ログイン">
          </div>
        </form>
        <div class="header-login-note">
          <p>プリンスホテルズ&amp;リゾーツ会員ページのご利⽤には、<a href="/membership/">SEIBU
            PRINCE CLUB</a>の会員登録が必要です。SEIBU PRINCE CLUB
            にご入会後、会員情報登録がお済みのお客さまはご利用いただけます。<br>※SEIBU PRINCE CLUBのWebお申込みは、お申込みと同時に「お客さま番号」を発番いたしますので、カードが届く前にマイページをご利用いただけます。</p>
          <p class="link"><a href="/membership/">会員制度・特典を見る</a></p>
        </div>
        <div class="mfp-close-bottom">
          <div class="mfp-close"></div>
        </div>
      </div>
    <!-- /.header =======--></header>
<script>
    (function($) {
        //サイト検索
var ref = location.href;
$('#site-search-ref-pc').val(ref.slice(0, ref.indexOf("#")));
$('#site-search-ref-sp').val(ref.slice(0, ref.indexOf("#")));
        
        $(function(){
            //初期値に次の日をセット
            var nextDate = new Date();
            nextDate.setDate(nextDate.getDate() + 1);
            $('#dateto').datepicker().datepicker('setDate', nextDate);
            //from変更時に次の日をセット
            $("#datefrom").change(function() {
                var nextDate = new Date($(this).datepicker('getDate'));
                nextDate.setDate(nextDate.getDate() + 1);
                $('#dateto').datepicker().datepicker('setDate', nextDate);
            });
            //検索ボタン押下時の処理
            $('#header-search-hotel-button').bind('click', function(){
                var baseUrl = "https://rsv.princehotels.co.jp/cgi-bin/ihonex/stay/search_plan.cgi";
                var width = window.innerWidth;
                var point = 736;
                if (width <= point) {
                    baseUrl = "https://rsv.princehotels.co.jp/cgi-bin/ihonex/stay/sp_search_plan.cgi";
                }
                
//                var cl_tbd = "1";
                var form = $('input[name="form"]').attr('value');
                var area = $('input[name="search:area"]').val();
                var hid = $('input[name="search:hid"]').val();
                var search_hid = (hid === 'ph')? '' : hid ;
                var chkin =  $('#datefrom').val().match(/\d+/g);
                var chkin_yy = chkin[0];
                var chkin_mm = chkin[1];
                var chkin_dd = chkin[2];
                var chkout =  $('#dateto').val().match(/\d+/g);
                var chkout_yy = chkout[0]
                var chkout_mm = chkout[1];
                var chkout_dd = chkout[2];
                var search_ninzu = $('select[name="search:ninzu"]').val();
                var rooms = $('select[name="rooms"]').val();
                var targetUrl = baseUrl + "?hid=" + hid + "&form=" + form + "&search:area=" + area  + "&search:hid=" + search_hid +  "&&chkin_yy=" + chkin_yy + "&chkin_mm=" + chkin_mm + "&chkin_dd=" + chkin_dd + "&chkout_yy=" + chkout_yy + "&chkout_mm=" + chkout_mm + "&chkout_dd=" + chkout_dd + "&search:ninzu=" + search_ninzu + "&rooms=" + rooms + '&search=1';
                var reserveWindow = window.open(targetUrl);
                reserveWindow.focus();
                return false;
            });
        });
    })(jQuery);

var navList = $('.header-nav').find('li');
var urlPath = $(location).attr('pathname');
var navUrl = "";
navList.each(function(index){
 navUrl = $(navList[index]).find('a').attr('href');
 if(navUrl == urlPath){
  $(navList[index]).addClass("current");
  console.log(navUrl);
 }
});
</script>
